"""Núcleo de processamento e lógica de negócio do PPT-Gen Studio."""

from core.engines import (
    build_presentation,
    calculate_slide_geometry,
    generate_pdf_preview_bytes,
    generate_pdf_thumbnail_bytes,
    generate_preview_bytes,
    generate_thumbnail_bytes,
    get_image_info,
    get_pdf_page_count,
    get_pdf_page_dimensions,
    load_image_with_orientation_and_rotation,
    parse_hex_color,
    render_pdf_page_to_image,
)
from core.models import (
    ConversionJob,
    ExportRequest,
    ExportResponse,
    PathInputRequest,
    RemoveItemsRequest,
    ReorderRequest,
    RotateRequest,
    SessionManifestDto,
    SlideGeometry,
    SlideItem,
    SlideItemDto,
)
from core.session import SessionManager
from core.sorter import (
    filter_supported_images,
    is_image_file,
    is_pdf_file,
    natural_sort_key,
    natural_sort_paths,
)

__all__ = [
    "ConversionJob",
    "ExportRequest",
    "ExportResponse",
    "PathInputRequest",
    "RemoveItemsRequest",
    "ReorderRequest",
    "RotateRequest",
    "SessionManager",
    "SessionManifestDto",
    "SlideGeometry",
    "SlideItem",
    "SlideItemDto",
    "build_presentation",
    "calculate_slide_geometry",
    "filter_supported_images",
    "generate_pdf_preview_bytes",
    "generate_pdf_thumbnail_bytes",
    "generate_preview_bytes",
    "generate_thumbnail_bytes",
    "get_image_info",
    "get_pdf_page_count",
    "get_pdf_page_dimensions",
    "is_image_file",
    "is_pdf_file",
    "load_image_with_orientation_and_rotation",
    "natural_sort_key",
    "natural_sort_paths",
    "parse_hex_color",
    "render_pdf_page_to_image",
]
